//go:build ignore

// Generate Spoon's typed palettes from its vendored resolved design tokens.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type tokenFile struct {
	Tokens map[string]struct {
		Type string `json:"type"`
		CSS  string `json:"css"`
	} `json:"tokens"`
}

type role struct {
	Name  string
	Field string
}

type themeSpec struct {
	Name string
	Var  string
}

var roles = []role{
	{Name: "bg", Field: "Bg"},
	{Name: "surface-1", Field: "Surface1"},
	{Name: "surface-2", Field: "Surface2"},
	{Name: "surface-3", Field: "Surface3"},
	{Name: "border", Field: "Border"},
	{Name: "text", Field: "Text"},
	{Name: "text-strong", Field: "TextStrong"},
	{Name: "text-muted", Field: "TextMuted"},
	{Name: "text-faint", Field: "TextFaint"},
	{Name: "accent", Field: "Accent"},
	{Name: "accent-2", Field: "Accent2"},
	{Name: "accent-rust", Field: "AccentRust"},
	{Name: "mix-target", Field: "MixTarget"},
	{Name: "success", Field: "Success"},
	{Name: "error", Field: "Error"},
	{Name: "warning", Field: "Warning"},
	{Name: "info", Field: "Info"},
	{Name: "syn-keyword", Field: "SynKeyword"},
	{Name: "syn-string", Field: "SynString"},
	{Name: "syn-var", Field: "SynVar"},
	{Name: "syn-func", Field: "SynFunc"},
	{Name: "syn-comment", Field: "SynComment"},
	{Name: "syn-number", Field: "SynNumber"},
}

var validHex = regexp.MustCompile(`^#[0-9a-fA-F]{6}$`)

var expectedRoles = func() map[string]struct{} {
	result := make(map[string]struct{}, len(roles))
	for _, role := range roles {
		result[role.Name] = struct{}{}
	}
	return result
}()

func main() {
	check := flag.Bool("check", false, "fail when palette_gen.go is not current")
	tokensDir := flag.String("tokens-dir", "tokens", "directory containing vendored token JSON")
	outputPath := flag.String("output", "palette_gen.go", "generated palette output path")
	flag.Parse()

	output, err := generate(*tokensDir)
	if err != nil {
		fail(err)
	}
	if *check {
		current, err := os.ReadFile(*outputPath)
		if err != nil {
			fail(err)
		}
		if !bytes.Equal(current, output) {
			fail(errors.New("palette_gen.go is stale; run go generate ./internal/tui/theme"))
		}
		return
	}
	if err := os.WriteFile(*outputPath, output, 0o644); err != nil {
		fail(err)
	}
}

func generate(tokensDir string) ([]byte, error) {
	themes := []themeSpec{
		{Name: "dark", Var: "Dark"},
		{Name: "light", Var: "Light"},
		{Name: "amber", Var: "Amber"},
	}
	palettes := make(map[string]map[string]string, len(themes))
	for _, theme := range themes {
		palette, err := readPalette(tokensDir, theme.Name)
		if err != nil {
			return nil, err
		}
		palettes[theme.Name] = palette
	}

	var source strings.Builder
	source.WriteString("// Code generated by gen.go from dark.tokens.json, light.tokens.json, and amber.tokens.json; DO NOT EDIT.\n\n")
	source.WriteString("package theme\n\n")
	source.WriteString("import \"github.com/charmbracelet/lipgloss\"\n\n")
	source.WriteString("// Palette is the complete terminal palette resolved from one design-system theme.\n")
	source.WriteString("type Palette struct {\n")
	for _, role := range roles {
		fmt.Fprintf(&source, "\t%s lipgloss.Color\n", role.Field)
	}
	source.WriteString("}\n\n")
	for _, theme := range themes {
		fmt.Fprintf(&source, "var %s = Palette{\n", theme.Var)
		for _, role := range roles {
			fmt.Fprintf(&source, "\t%s: lipgloss.Color(%q),\n", role.Field, palettes[theme.Name][role.Name])
		}
		source.WriteString("}\n\n")
	}

	return format.Source([]byte(source.String()))
}

func readPalette(tokensDir, theme string) (map[string]string, error) {
	path := filepath.Join(tokensDir, theme+".tokens.json")
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", theme, err)
	}
	var file tokenFile
	if err := json.Unmarshal(contents, &file); err != nil {
		return nil, fmt.Errorf("%s: invalid JSON: %w", theme, err)
	}
	for name, token := range file.Tokens {
		if token.Type != "color" {
			continue
		}
		if _, expected := expectedRoles[name]; !expected {
			return nil, fmt.Errorf("%s: unexpected color role %s", theme, name)
		}
	}
	palette := make(map[string]string, len(roles))
	for _, role := range roles {
		token, ok := file.Tokens[role.Name]
		if !ok || token.CSS == "" {
			return nil, fmt.Errorf("%s: missing role %s", theme, role.Name)
		}
		if !validHex.MatchString(token.CSS) {
			return nil, fmt.Errorf("%s: invalid hex for role %s: %q", theme, role.Name, token.CSS)
		}
		palette[role.Name] = token.CSS
	}
	return palette, nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
