// Code generated by gen.go from dark.tokens.json, light.tokens.json, and amber.tokens.json; DO NOT EDIT.

package theme

import "github.com/charmbracelet/lipgloss"

// Palette is the complete terminal palette resolved from one design-system theme.
type Palette struct {
	Bg         lipgloss.Color
	Surface1   lipgloss.Color
	Surface2   lipgloss.Color
	Surface3   lipgloss.Color
	Border     lipgloss.Color
	Text       lipgloss.Color
	TextStrong lipgloss.Color
	TextMuted  lipgloss.Color
	TextFaint  lipgloss.Color
	Accent     lipgloss.Color
	Accent2    lipgloss.Color
	AccentRust lipgloss.Color
	MixTarget  lipgloss.Color
	Success    lipgloss.Color
	Error      lipgloss.Color
	Warning    lipgloss.Color
	Info       lipgloss.Color
	SynKeyword lipgloss.Color
	SynString  lipgloss.Color
	SynVar     lipgloss.Color
	SynFunc    lipgloss.Color
	SynComment lipgloss.Color
	SynNumber  lipgloss.Color
}

var Dark = Palette{
	Bg:         lipgloss.Color("#191919"),
	Surface1:   lipgloss.Color("#1e1e1e"),
	Surface2:   lipgloss.Color("#252526"),
	Surface3:   lipgloss.Color("#2d2d2d"),
	Border:     lipgloss.Color("#3c3c3c"),
	Text:       lipgloss.Color("#d4d4d4"),
	TextStrong: lipgloss.Color("#f5f5f5"),
	TextMuted:  lipgloss.Color("#9a9a9a"),
	TextFaint:  lipgloss.Color("#858585"),
	Accent:     lipgloss.Color("#4ec9b0"),
	Accent2:    lipgloss.Color("#e06c75"),
	AccentRust: lipgloss.Color("#ce9178"),
	MixTarget:  lipgloss.Color("#ffffff"),
	Success:    lipgloss.Color("#74a55e"),
	Error:      lipgloss.Color("#ff5b48"),
	Warning:    lipgloss.Color("#ffa500"),
	Info:       lipgloss.Color("#6fa8c7"),
	SynKeyword: lipgloss.Color("#569cd6"),
	SynString:  lipgloss.Color("#ce9178"),
	SynVar:     lipgloss.Color("#9cdcfe"),
	SynFunc:    lipgloss.Color("#dcdcaa"),
	SynComment: lipgloss.Color("#74a55e"),
	SynNumber:  lipgloss.Color("#b5cea8"),
}

var Light = Palette{
	Bg:         lipgloss.Color("#f1e7c4"),
	Surface1:   lipgloss.Color("#ece1b8"),
	Surface2:   lipgloss.Color("#e6dcb2"),
	Surface3:   lipgloss.Color("#e0d5a8"),
	Border:     lipgloss.Color("#c7ba85"),
	Text:       lipgloss.Color("#3a3527"),
	TextStrong: lipgloss.Color("#2a2617"),
	TextMuted:  lipgloss.Color("#605b47"),
	TextFaint:  lipgloss.Color("#65604b"),
	Accent:     lipgloss.Color("#1f6659"),
	Accent2:    lipgloss.Color("#8d3740"),
	AccentRust: lipgloss.Color("#874a30"),
	MixTarget:  lipgloss.Color("#000000"),
	Success:    lipgloss.Color("#086326"),
	Error:      lipgloss.Color("#9d2b20"),
	Warning:    lipgloss.Color("#7d4800"),
	Info:       lipgloss.Color("#205d7d"),
	SynKeyword: lipgloss.Color("#274a86"),
	SynString:  lipgloss.Color("#8a4326"),
	SynVar:     lipgloss.Color("#2f3f6e"),
	SynFunc:    lipgloss.Color("#6a531f"),
	SynComment: lipgloss.Color("#525f36"),
	SynNumber:  lipgloss.Color("#2f5f45"),
}

var Amber = Palette{
	Bg:         lipgloss.Color("#0f0e0d"),
	Surface1:   lipgloss.Color("#1a1815"),
	Surface2:   lipgloss.Color("#221f1a"),
	Surface3:   lipgloss.Color("#2b271f"),
	Border:     lipgloss.Color("#332e26"),
	Text:       lipgloss.Color("#e2d9c8"),
	TextStrong: lipgloss.Color("#f1e7c4"),
	TextMuted:  lipgloss.Color("#a89c86"),
	TextFaint:  lipgloss.Color("#948a76"),
	Accent:     lipgloss.Color("#d4a017"),
	Accent2:    lipgloss.Color("#e06c75"),
	AccentRust: lipgloss.Color("#ce9178"),
	MixTarget:  lipgloss.Color("#ffffff"),
	Success:    lipgloss.Color("#86b86b"),
	Error:      lipgloss.Color("#e4635a"),
	Warning:    lipgloss.Color("#e08a2b"),
	Info:       lipgloss.Color("#6fa8c7"),
	SynKeyword: lipgloss.Color("#6ea7dd"),
	SynString:  lipgloss.Color("#d29a6a"),
	SynVar:     lipgloss.Color("#9ec7e8"),
	SynFunc:    lipgloss.Color("#d9c78a"),
	SynComment: lipgloss.Color("#8faf72"),
	SynNumber:  lipgloss.Color("#b3c99a"),
}
