package config

// configReadme is written next to a bootstrapped config.json so the knobs are
// documented where the user will look for them. Regenerated by `spoon setup`.
const configReadme = `# spoon configuration

This directory was created automatically on spoon's first run. Nothing here is
required — delete config.json and spoon regenerates it with defaults on the
next run. Set SPOON_NO_CONFIG=1 to ignore the file entirely.

## Files

- ` + "`config.json`" + ` — settings (documented below). Precedence everywhere:
  command-line flags > environment variables > this file > built-in defaults.
- ` + "`spoon.db`" + ` — the global store: every repo/fork/compare spoon has seen,
  shared by all commands. Compares are content-addressed: an entry serves
  until its fork is pushed again, then the refresh overwrites it. Safe to
  delete (spoon refetches); grows with the repos you scan.
- ` + "`README.md`" + ` — this file. Rewritten by ` + "`spoon setup`" + `.

Locations: per-user under $XDG_CONFIG_HOME/spoon (default ~/.config/spoon).
Hosts without a home directory use /etc/spoon for config and /var/lib/spoon
for the store. /etc/spoon/config.json also acts as an admin-provided defaults
layer for users who have no personal config.

## config.json fields

- ` + "`version`" + ` — schema version; leave as written.
- ` + "`forge.provider`" + ` — "github" or "gitlab". Empty = auto-detect from the
  repo URL/flags each run (the default; usually what you want).
- ` + "`forge.host`" + ` — self-hosted GitLab/GHES hostname. Empty = the public host.
- ` + "`github.tokens`" + ` — extra GitHub tokens for parallel rate budgets.
  OPTIONAL and normally unnecessary: spoon uses the gh CLI login or
  GH_TOKEN/GITHUB_TOKEN from the environment. If you do put tokens here,
  chmod 600 config.json (spoon refuses a group/other-readable token file).
- ` + "`github.requestsPerMinute`" + ` — client-side pacing cap (default 500, max 900).
- ` + "`github.proxy`" + ` — optional ProxyScrape-backed transport: enabled,
  apiKeyFile/staticFile (paths to 0600 files; contents are never copied
  here), whitelistPublicIp, cacheTtl. Off by default.
- ` + "`embedder.backend`" + ` — "fastembed" (the only backend; empty means the
  same). Powers semantic indexing/search in spn. The model (~30 MB BGE
  small EN v1.5) downloads itself on first use; the TUI's clustering uses a
  built-in lexical embedder and needs nothing.
- ` + "`embedder.model`" + `, ` + "`embedder.cacheDir`" + `, ` + "`embedder.maxLength`" + `,
  ` + "`embedder.batchSize`" + ` — fastembed tuning; defaults are fine.

## Environment variables

| Variable | Effect |
|---|---|
| SPOON_NO_CONFIG=1 | Ignore config.json entirely |
| SPOON_NO_EMBED=1 | Skip embedding/semantic indexing on spn forks list |
| SPOON_NO_RESERVE=1 | Drain the full API rate budget (no reserve floor) |
| SPOON_DEBUG=1 | Verbose pipeline/rate-limit debugging |
| SPOON_GITHUB_RPM | Override github.requestsPerMinute |
| SPOON_GH_COOKIE | Session cookie for the unsupported HTML web-diff fallback |
| SPOON_FASTEMBED_MODEL | Override embedder.model |
| SPOON_FASTEMBED_CACHE | Override embedder.cacheDir |
| SPOON_FASTEMBED_SHA256 | Expected SHA-256 of the fastembed model archive |
| SPOON_PROXY_KEY_PATH | ProxyScrape API-key file adopted by spoon setup |
| SPOON_PROXY_STATIC_PATH | ProxyScrape static-pool file adopted by spoon setup |
| TURSO_DATABASE_URL | Sync the store to a remote Turso database |
| TURSO_AUTH_TOKEN | Auth token for TURSO_DATABASE_URL |
| GH_TOKEN / GITHUB_TOKEN | GitHub auth (or use: gh auth login) |
| GITLAB_TOKEN | GitLab auth (or use: glab auth login) |
| ONNX_PATH | Path to libonnxruntime.so if not on the loader path |
| NO_COLOR | Disable colors |

## Changing things

Edit config.json directly (spoon validates on load and tells you what is
wrong), or re-run ` + "`spoon setup`" + ` to re-detect credentials and the embedder
and rewrite the file. ` + "`--refresh`" + ` on any command bypasses cached reads for
that run.
`
