package config

// configReadme is written next to a bootstrapped config.json so the knobs are
// documented where the user will look for them. Regenerated by `spoon setup`.
const configReadme = `# spoon configuration

This directory was created automatically on spoon's first run. Nothing here is
required — delete config.json and spoon regenerates it with defaults on the
next run. Set SPOON_NO_CONFIG=1 to ignore the file entirely.

## Files

- ` + "`config.json`" + ` — settings (documented below). Precedence everywhere:
  command-line flags > environment variables > this file > built-in defaults.
- ` + "`spoon.db`" + ` — the global store: every repo/fork/compare spoon has seen,
  shared by all commands, plus the semantic index and the cached Voyage
  responses. Compares are content-addressed: an entry serves until its fork is
  pushed again, then the refresh overwrites it. Safe to delete (spoon refetches),
  though deleting it discards paid Voyage results and the next run re-buys them;
  grows with the repos you scan.
- ` + "`README.md`" + ` — this file. Rewritten by ` + "`spoon setup`" + `.

Locations: per-user under $XDG_CONFIG_HOME/spoon (default ~/.config/spoon).
Hosts without a home directory use /etc/spoon for config and /var/lib/spoon
for the store. /etc/spoon/config.json also acts as an admin-provided defaults
layer for users who have no personal config.

## config.json fields

- ` + "`version`" + ` — schema version. Version 2 means the optional ` + "`ui`" + ` section
  (theme, color, glyphs) is available; old files without it migrate losslessly
  when saved by the in-TUI editor.
- ` + "`forge.provider`" + ` — "github" or "gitlab". Empty = auto-detect from the
  repo URL/flags each run (the default; usually what you want).
- ` + "`forge.host`" + ` — self-hosted GitLab/GHES hostname. Empty = the public host.
- ` + "`github.tokens`" + ` — extra GitHub tokens for parallel rate budgets.
  OPTIONAL and normally unnecessary: spoon uses the gh CLI login or
  GH_TOKEN/GITHUB_TOKEN from the environment. If you do put tokens here,
  chmod 600 config.json (spoon refuses a group/other-readable token file).
- ` + "`github.requestsPerMinute`" + ` — client-side pacing cap (default 300, max 900).
- ` + "`github.proxy`" + ` — optional ProxyScrape-backed transport: enabled,
  apiKeyFile/staticFile (paths to 0600 files; contents are never copied
  here), whitelistPublicIp, cacheTtl. Off by default.
- ` + "`ui.theme`" + ` — terminal palette: "dark", "light", or "amber". Empty =
  dark. ` + "`SPOON_TUI_THEME`" + ` overrides it.
- ` + "`ui.color`" + ` — terminal color profile: "truecolor", "ansi256",
  "ansi16", "ansi8", "mono", or "no-color". Empty = truecolor; ` + "`SPOON_TUI_COLOR`" + `
  overrides it, while non-empty ` + "`NO_COLOR`" + ` disables color when no explicit
  profile is set.
  ` + "`spn`" + ` deliberately gives non-empty ` + "`NO_COLOR`" + ` precedence over
  ` + "`SPOON_TUI_COLOR`" + ` for pipeline safety, unlike the interactive TUI.
- ` + "`ui.glyphs`" + ` — "unicode" (default) or "ascii"; ` + "`SPOON_TUI_GLYPHS`" + `
  overrides it.
- ` + "`embedder.backend`" + ` — "fastembed" (the only backend; empty means the
  same). Powers semantic indexing/search in spn. The model (~30 MB BGE
  small EN v1.5) downloads itself on first use; the TUI's clustering uses a
  built-in lexical embedder and needs nothing.
- ` + "`embedder.model`" + `, ` + "`embedder.cacheDir`" + `, ` + "`embedder.maxLength`" + `,
  ` + "`embedder.batchSize`" + ` — fastembed tuning; defaults are fine.
- ` + "`embedder.voyage`" + ` — OPTIONAL Voyage AI, the one part of spoon that calls
  an external service. It runs **in addition to** fastembed, not instead of it:
  both models' vectors are stored side by side, so enabling or disabling Voyage
  never invalidates the local index. It adds a voyage-code-3 semantic index
  (` + "`spn search --voyage`" + `) and cross-encoder reranking for
  ` + "`spn forks list --query`" + `, ` + "`spn search`" + `, and the TUI's ` + "`R`" + ` fork
  ranking (` + "`/`" + ` stays a local substring filter and never calls out).
  Fields: apiKeyFile (path to a 0600 file holding the key — the key itself is
  never stored here), embedModel, rerankModel, outputDimension (256/512/1024/2048;
  1024 default), baseUrl, disabled.
  Voyage is billed per token, so responses are cached in spoon.db and re-runs
  re-request nothing unchanged. It stays OFF unless both a key resolves and the
  store is writable — with nowhere durable to keep results, every run would pay
  again for answers it had to throw away.
- ` + "`ui.theme`" + ` — terminal palette: dark, light, or amber. ` + "`ui.color`" + `
  selects truecolor, ansi256, ansi16, ansi8, mono, or no-color; ` + "`ui.glyphs`" + `
  selects unicode or ascii. Use the in-TUI Settings editor (comma key) to inspect
  the effective value and its source.


## Environment variables

| Variable | Effect |
|---|---|
| SPOON_NO_CONFIG=1 | Ignore config.json entirely |
| SPOON_NO_EMBED=1 | Skip embedding/semantic indexing on spn forks list |
| SPOON_LOCAL_BRANCH_SCAN=1 | Include local git branches in spn fork scans |
| VOYAGE_AI_API_KEY | Enable Voyage AI embeddings + reranking (see embedder.voyage) |
| VOYAGE_API_KEY | Accepted as a fallback (what Voyage's own SDKs read) |
| SPOON_VOYAGE_API_KEY_FILE | Override embedder.voyage.apiKeyFile (path to a 0600 key file) |
| SPOON_VOYAGE_AUTO_INDEX=1 | Embed every listed fork through Voyage automatically (billed) |
| SPOON_NO_VOYAGE=1 | Skip Voyage even when a key is set; fastembed still runs |
| SPOON_SECRET_STORE | "keyring" (default) keeps GitHub tokens in the OS keyring, with "keyring:<entry>" references in this file; "file" keeps them inline in this 0600 file. Falls back to inline, with a warning, when no keyring is usable |
| SPOON_VOYAGE_NO_CACHE=1 | Bypass the cached Voyage responses (re-pays for them) |
| SPOON_VOYAGE_DIM | Override embedder.voyage.outputDimension |
| SPOON_VOYAGE_EMBED_MODEL | Override embedder.voyage.embedModel |
| SPOON_VOYAGE_RERANK_MODEL | Override embedder.voyage.rerankModel |
| SPOON_VOYAGE_BASE_URL | Override the Voyage API root (gateways, testing) |
| SPOON_NO_RESERVE=1 | Drain the full API rate budget (no reserve floor) |
| SPOON_DEBUG=1 | Verbose pipeline/rate-limit debugging |
| SPOON_GITHUB_RPM | Override github.requestsPerMinute |
| SPOON_GH_COOKIE | Session cookie for the unsupported HTML web-diff fallback |
| SPOON_FASTEMBED_MODEL | Override embedder.model |
| SPOON_FASTEMBED_CACHE | Override embedder.cacheDir |
| SPOON_AUTO_INDEX | Embed fork lists with fastembed automatically (default on) |
| SPOON_FASTEMBED_SHA256 | Expected SHA-256 of the fastembed model archive |
| SPOON_PROXY_KEY_PATH | ProxyScrape API-key file adopted by spoon setup |
| SPOON_PROXY_STATIC_PATH | ProxyScrape static-pool file adopted by spoon setup |
| TURSO_DATABASE_URL | Sync the store to a remote Turso database |
| TURSO_AUTH_TOKEN | Auth token for TURSO_DATABASE_URL |
| GH_TOKEN / GITHUB_TOKEN | GitHub auth (or use: gh auth login) |
| GITLAB_TOKEN | GitLab auth (or use: glab auth login) |
| ONNX_PATH | Path to libonnxruntime.so if not on the loader path |
| NO_COLOR | Disable colors |
| SPOON_TUI_THEME | TUI palette: dark, light, or amber; overrides ui.theme |
| SPOON_TUI_COLOR | TUI color profile: truecolor, ansi256, ansi16, ansi8, mono, or no-color |
| SPOON_TUI_GLYPHS | TUI glyph profile: unicode or ascii |

## Changing things

Edit config.json directly (spoon validates on load and tells you what is
wrong), use the in-TUI Settings editor (comma key) to inspect and safely save the
loaded layer, or re-run ` + "`spoon setup`" + ` to re-detect credentials and
the embedder and rewrite the file. ` + "`--refresh`" + ` on any command bypasses
cached reads for that run.
`
